[package]
name = "dx-ether-rs"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "dx_ether_rs"
path = "src/lib.rs"

[dependencies]
dioxus = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
gloo-timers = { workspace = true }
alloy-primitives = { workspace = true }
